function result = func_f2(x,y)
result = -(func_lamda(x,y) + 2 .* func_nu(x,y)) .* (2 .* x .* (x - 1))...
         -(func_lamda(x,y) + func_nu(x,y)) .* (pi^2 .* cos(pi .* x) .* cos(pi .* y))...
         -func_nu(x,y) .* (2 .* y .* (y - 1));
end